// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: 'AIzaSyBc_-iF64B7fnauGQi16q6UKZQXhq7C0zY',
      authDomain: "szf-app.firebaseapp.com",
      projectId: "szf-app",
      storageBucket: "szf-app.appspot.com",
      messagingSenderId: "72052674228",
      appId: "1:182921035370:web:82c2b1075ffe14992ad413",
      measurementId: "G-C54LRT9LGJ");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjpFIDKgS68YJELZuu89YcStv3E6lsymQ',
    appId: "1:896622122947:android:fbf60bc62c2b9a49bb4f76",
    messagingSenderId: "896622122947",
    projectId: "sportopia-74ea2",
    storageBucket: "sportopia-74ea2.appspot.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAciW5aOsjmqj8sbHFpbUcn-tSG9hLuZWM',
    appId: "1:896622122947:ios:5820b29cff54eb80bb4f76",
    messagingSenderId: "896622122947",
    projectId: "sportopia-74ea2",
    storageBucket: "sportopia-74ea2.appspot.com",
    iosBundleId: 'com.sportopia.app',
  );
}
